# Generated by Django 4.2.13 on 2024-07-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_recipeingredient_ingredientquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.ManyToManyField(related_name='category_recipes', to='recipes.category'),
        ),
    ]
