# Generated by Django 4.2.13 on 2024-07-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_recipe_category_recipe_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='recipe',
        ),
    ]
