# Generated by Django 4.2.13 on 2024-07-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_post_comment_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='Please enter each new step on\n    a new line preceded by a hyphen (-) or number (e.g. 1:..., 2:...)).', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ManyToManyField(blank=True, related_name='category_recipes', to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_cook_time',
            field=models.DurationField(blank=True, default=None, help_text='Please enter the total cook time in the format HH:MM:SS (e.g., 01:30:00 for 1 hour and 30 minutes).', null=True),
        ),
    ]
